# Site settings
title: Tim M. Szewczyk
email: tim.szewczyk@gmail.com
description: ""

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://Sz-Tim.github.io" # the base hostname & protocol for your site
github_username:  Sz-Tim

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jemoji

